ARG ROS_BASE_REF
FROM ${ROS_BASE_REF}

LABEL org.ros2-riscv.component="humble-gazebo"

RUN curl --fail --silent --show-error --location --max-time 60 \
        https://packages.osrfoundation.org/gazebo.gpg \
        --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg \
    && printf '%s  %s\n' \
        15d0300460e0c9c0efb21fa9770c0bf228988a07d71c4fac985c2161954a25a4 \
        /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg | sha256sum --check -
RUN printf '%s\n' 'deb [arch=amd64 signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] https://packages.osrfoundation.org/gazebo/ubuntu-stable jammy main' \
        > /etc/apt/sources.list.d/gazebo-stable.list \
    && apt-get update \
    && apt-get install -y --no-remove --no-install-recommends \
        gz-harmonic ros-humble-ros-gzharmonic ros-humble-rviz2 \
        ros-humble-robot-state-publisher libgl1-mesa-dri libglx-mesa0 \
        ros-humble-rqt-graph ros-humble-rqt-console \
    && rm -rf /var/lib/apt/lists/*
