<?xml version="1.0"?>
<package format="3">
  <name>weather_srv</name>
  <version>0.1.0</version>
  <description>C++ weather query service.</description>
  <maintainer email="duoqilai@outlook.com">DuoQilai</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>weather_interfaces</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
