<?xml version="1.0"?>
<package format="3">
  <name>sensor_pub_cpp</name>
  <version>0.1.0</version>
  <description>ROS 2 C++ custom sensor message publisher.</description>
  <maintainer email="duoqilai@outlook.com">DuoQilai</maintainer>
  <license>BSD</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_interfaces</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
