<?xml version="1.0"?>
<package format="3">
  <name>hello_pkg_cpp</name>
  <version>0.1.0</version>
  <description>ROS 2 C++ node, logger, and odometry examples.</description>
  <maintainer email="duoqilai@outlook.com">DuoQilai</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
