<?xml version="1.0"?>
<package format="3">
  <name>service_demo_lab_cpp</name>
  <version>0.1.0</version>
  <description>C++ AddTwoInts service with timeout and retry behavior.</description>
  <maintainer email="duoqilai@outlook.com">DuoQilai</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>example_interfaces</depend>
  <depend>rclcpp</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
