<?xml version="1.0"?>
<package format="3">
  <name>lifecycle_demo_cpp</name>
  <version>0.1.0</version>
  <description>ROS 2 C++ lifecycle node for the Stage 3 course.</description>
  <maintainer email="duoqilai@outlook.com">DuoQilai</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>lifecycle_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
